image: Visual Studio 2022

build: off

init:
  - ps: |
      $passwd = ConvertTo-SecureString "Password123!" -AsPlainText -Force
      New-LocalUser "rdpuser" -Password $passwd -FullName "RDP User" -Description "User for RDP session"
      Add-LocalGroupMember -Group "Administrators" -Member "rdpuser"

on_finish:
  - ps: |
      $appveyorAccountName = $env:APPVEYOR_ACCOUNT_NAME
      $appveyorProjectSlug = $env:APPVEYOR_PROJECT_SLUG
      $appveyorBuildVersion = $env:APPVEYOR_BUILD_VERSION
      $url = "https://ci.appveyor.com/api/projects/$appveyorAccountName/$appveyorProjectSlug/builds/$appveyorBuildVersion/rdp"
      $rdp = Invoke-RestMethod -Method POST -Uri $url -Headers @{"Authorization"="Bearer $env:APPVEYOR_API_TOKEN"}
      Write-Host "RDP link: $($rdp.url)"
