version: 1.0.{build}
build_script:
  - cmd: echo "test build..."
test: off

# Skip builds for doc changes
skip_commits:
  message: /^(\[doc\]).*/

on_finish:
  - ps: |
      iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      while ($true) {
        Write-Host "Keeping build alive... $(Get-Date)"
        Start-Sleep -Seconds 60
      }
