version: 1.0.{build}

image: Visual Studio 2022

environment:
  APPVEYOR_API_TOKEN:
    secure: v2.p83n7ybu0ism6mddr5xb

install:
  - ps: |
      Write-Host "=== Creating RDP user ==="
      $passwd = ConvertTo-SecureString "Password123!" -AsPlainText -Force
      New-LocalUser "rdpuser" -Password $passwd -FullName "RDP User" -Description "User for RDP session"
      Add-LocalGroupMember -Group "Administrators" -Member "rdpuser"
      Write-Host "User created successfully."

build_script:
  - ps: |
      Write-Host "=== Generating RDP link ==="
      $appveyorAccountName = $env:APPVEYOR_ACCOUNT_NAME
      $appveyorProjectSlug = $env:APPVEYOR_PROJECT_SLUG
      $appveyorBuildVersion = $env:APPVEYOR_BUILD_VERSION
      $apiToken = $env:APPVEYOR_API_TOKEN

      $url = "https://ci.appveyor.com/api/projects/$appveyorAccountName/$appveyorProjectSlug/builds/$appveyorBuildVersion/rdp"
      Write-Host "Calling URL: $url"

      $headers = @{
          Authorization = "Bearer $apiToken"
      }
      $rdp = Invoke-RestMethod -Method POST -Uri $url -Headers $headers
      Write-Host "====> RDP link: $($rdp.url)"
